package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hello-time",
    srcs = ["hello-time.cc"],
    hdrs = ["include/hello-time.h"],
    #includes=["include",],
    #include_prefix="include",
)
